apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-spring-k8s
spec:
  selector:
    matchLabels:
      app: hello-spring-k8s
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-spring-k8s
    spec:
      containers:
        - name: hello-spring-k8s
          image: trung2910/hello-spring-k8s:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080